"""
Django settings for highlevel_api project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kgk=n01#9si@p5det2tyxu-lqq%7f11#*=ovj!ewgup)z%zh$9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Default: Stores sessions in DB
SESSION_COOKIE_SECURE = False  # Set to True if using HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# HIGHLEVEL_CLIENT_ID = "65c0a9a4277b2961322c545a-ls8q934d"
# HIGHLEVEL_CLIENT_SECRET = "94af4663-c0c7-4340-9ce5-39b38e88c146"
# HIGHLEVEL_API_BASE_URL = "https://services.leadconnectorhq.com"
# HIGHLEVEL_REDIRECT_URI = "http://127.0.0.1/"  # Or use "https://google.com"
# HIGHLEVEL_ACCESS_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBfdTc0MG5lWm1ENiJ9.eyJhdXRoQ2xhc3MiOiJNYXJrZXRwbGFjZUNsaWVudCIsImF1dGhDbGFzc0lkIjoiNjVjMGE5YTQyNzdiMjk2MTMyMmM1NDVhIiwiY2hhbm5lbCI6Ik9BVVRIIiwic291cmNlIjoiT0FVVEhfQ0xJRU5UIiwic291cmNlSWQiOiI2MWY4ZTM4M2EyOTJkNGRlZDZjY2IzMTAiLCJtYXJrZXRwbGFjZUNsaWVudE1ldGEiOnsiZGV2ZWxvcGVySWQiOiI2MWY4ZTM4M2EyOTJkNGRlZDZjY2IzMTAiLCJ0b2tlbklkIjoiZDQyYmMyZmUtZWY3ZS00NTI1LWJhMmEtM2IzMzkxNDFjNWNjIn0sImlhdCI6MTc0MTE5NzM1OCwiZXhwIjoxNzQxMjgzNzU4fQ.YiOZMHNtuBuPU0J0qegp15-NvnRKsgBrW9JV4VAeKaZohVbtJSiW0m9SqxfGg4lfnTfm17duqQCMoA87CVkr0woZ1O29GVzIk6VDsH5s6UM-uzRYduK9zl87oJxPwDzYS8u_xf-WtWpuxsZOjx43csS4KJvQ99cNgyZYToAQNUKeQVWNNPpac6N-fxnMxWxcqEhEUjwOZGHZdDjfKGmU2MbcloCnMeVD4zlZRgPzhI-OHzdpwHSfb4pgwB_-zULvkvJ5tLqmq9RevUIi_9H5s1O0NWbufSxApASPg6pfec7KR49LcvYq3JWOiz4RI9ilaqqLqczncIgjPZiC3wml95ujCq9AcrvRmZfiw6SafSxxRmJPDwqvH_KqroA8cKeEDSzGbVL4pC9CjX9pwJd5uKA6TSzC2NS3fm-9iFkOLrfYW44geem3TZkwrUDV6VYoID-s-Z5-kblQRzuDt4N8v-uGR723fuglksCM6Qt62qWlyXnW1uUEIjYyRgJFHAtu-gpGZso6Kv_KJn_ccu8MixPWUQHQOfx4OSdsFA2PnSPfqemSqfJ-kSZpzXOeqnCNRkvEUlOyWcdbTqimHLFtS4dNOzql6TD_bh5fcSMjxpkQ4p0t7ISjNxNsKlcbUr5ajXqjGVz3D_yBDvczC-dEbBcJnUBNo6SCUTC9VyHaAnc"  # Replace after obtaining it
import os



CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
REDIRECT_URI = os.getenv("REDIRECT_URI")
BASE_URL = os.getenv("BASE_URL")



ROOT_URLCONF = 'highlevel_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'highlevel_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
